
import Header from './Header';
import Footer from './Footer';

const PrivacyPolicyPage = () => {
  return (
    <div className="min-h-screen bg-gray-50">
      <Header />
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="bg-white rounded-lg shadow-sm p-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-6">Privacy Policy</h1>
          <p className="text-gray-600 mb-8">Last updated: June 5th 2025</p>
          
          <div className="prose max-w-none">
            <p className="mb-6">This Privacy Policy describes our policies and procedures on the collection, use and disclosure of your information when you use the Service and tells you about your privacy rights and how the law protects you.</p>
            <p className="mb-8">We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Interpretation and Definitions</h2>
            
            <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">Interpretation</h3>
            <p className="mb-4">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

            <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">Definitions</h3>
            <p className="mb-4">For the purposes of this Privacy Policy:</p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to medikart.store.</li>
              <li><strong>Cookies</strong> are small files that are placed on your computer, mobile device, or any other device by a website, containing the details of your browsing history on that website among its many uses.</li>
              <li><strong>Country</strong> refers to Kerala, India</li>
              <li><strong>Device</strong> means any device that can access the Service, such as a computer, a cellphone, or a digital tablet.</li>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong> refers to the Website.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
              <li><strong>Website</strong> refers to medikart.store, accessible from https://medikar.store/</li>
              <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>

            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Collecting and Using Your Personal Data</h2>
            
            <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">Types of Data Collected</h3>
            
            <h4 className="text-lg font-semibold text-gray-900 mt-4 mb-2">Personal Data</h4>
            <p className="mb-4">While using Our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:</p>
            <ul className="list-disc pl-6 mb-6">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Address, State, Province, ZIP/Postal code, City</li>
              <li>Usage Data</li>
            </ul>

            <h4 className="text-lg font-semibold text-gray-900 mt-4 mb-2">Usage Data</h4>
            <p className="mb-4">Usage Data is collected automatically when using the Service.</p>
            <p className="mb-6">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers, and other diagnostic data.</p>

            <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">Information from Third-Party Social Media Services</h3>
            <p className="mb-4">The Company allows you to create an account and log in to use the Service through the following Third-party Social Media Services:</p>
            <ul className="list-disc pl-6 mb-6">
              <li>Google</li>
              <li>Facebook</li>
              <li>Instagram</li>
              <li>Twitter</li>
              <li>LinkedIn</li>
            </ul>

            <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">Tracking Technologies and Cookies</h3>
            <p className="mb-4">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. The technologies we use may include:</p>
            <ul className="list-disc pl-6 mb-6">
              <li><strong>Cookies or Browser Cookies:</strong> A cookie is a small file placed on Your Device.</li>
              <li><strong>Web Beacons:</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons.</li>
            </ul>

            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Use of Your Personal Data</h2>
            <p className="mb-4">The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc pl-6 mb-6">
              <li>To provide and maintain our Service, including monitoring the usage of our Service.</li>
              <li>To manage Your Account: to manage your registration as a user of the Service.</li>
              <li>For the performance of a contract: the development, compliance, and undertaking of the purchase contract for the products, items or services you have purchased.</li>
              <li>To contact you: To contact you by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
              <li>To provide you with news, special offers, and general information about other goods, services, and events.</li>
              <li>To manage your requests: To attend to and manage your requests to us.</li>
            </ul>

            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Retention of Your Personal Data</h2>
            <p className="mb-6">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>

            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Security of Your Personal Data</h2>
            <p className="mb-6">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage, is 100% secure. While we strive to use commercially acceptable means to protect Your Personal Data, we cannot guarantee its absolute security.</p>

            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Children's Privacy</h2>
            <p className="mb-6">Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us.</p>

            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Changes to this Privacy Policy</h2>
            <p className="mb-6">We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. We will let you know via email and/or a prominent notice on our Service, before the change becoming effective.</p>

            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Contact Us</h2>
            <p className="mb-4">If you have any questions about this Privacy Policy, you can contact us:</p>
            <p className="mb-6">By email: medikart.rk@gmail.com</p>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default PrivacyPolicyPage;